apiVersion: v2
name: securityrat
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - condition: mysql.enabled
    name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 9.4.1
